### ISSUE TITLE
Might need destfile rather than dest_file in call to utils::download.file in thredds.R Line 115

### ISSUE THREAD

**Issue by ClintBlight** [edwardlavender/fvcom.tbx#1]
Hi Ed,

I've done some stuff before with linking R to more old school tide predictions from POLPRED, so when saw Tweet about fvcom.tbx it caught my eye and look thought I'd take a look. It downloaded + installed OK and I started trying out a couple of things in the vignette.

Just to let you know that, at least on my machine, the example call in the help for thredds_download  kicks up this error:

Unable to download file20190702. File name identified for this file minch2_20190702_0008.nc. URL obtained for this file: https://thredds.sams.ac.uk/thredds/fileServer/scoats-westcoms1/Archive/netcdf_2019/minch2_20190702_0008.nc. Error message followinf download.file(...): Error in utils::download.file(url = url, dest_file = paste0(dest_file, : argument "destfile" is missing, with no default 
 
A quick check indicates that might need "destfile" rather than "dest_file" in the call to utils::download.file in thredds.R Line 115

https://github.com/edwardlavender/fvcom.tbx/blob/1e0a77f457a5eaf8d4b0fdead31435e9f844cbb0/R/thredds.R#L115

cheers

Clint

**Comment by edwardlavender** [comment]
Hi Clint, 
Many thanks for getting in touch and for flagging up this issue so helpfully. You are quite right. I changed the destfile input recently (obviously in too much of a rush) and it's subsequently avoided the CMD checks through which it's not run. I've now fixed the input to download.file(). Many apologies for the bug! 
Best wishes,
Ed
