### ISSUE TITLE
Fatal error trying to open files downloaded via thredds_download()

### ISSUE THREAD

**Issue by morgane-pommier** [edwardlavender/fvcom.tbx#2]
Hi Edward, 

First of all, thank you for pointing me to the fvcom.tbx package, it allowed me to easily download the files I needed.

However, I run into an error trying to open the .nc files and was wondering if you ever came across similar issues with the WestCOMS data.
Basically, the files downloaded via fvcom.tbx using the thredds_download function lead to a fatal error and R crashes when trying to open then (using nc_open), while it doesn't with files manually downloaded from the same directory. I tried the solution suggested in [this post](https://stackoverflow.com/questions/51911544/r-crashes-while-opening-netcdf-file), specifying the mode as `wb` in the download function, but without success.

Did you ever encounter this problem with the WestCOMS data ?
For information, I am accessing data from [this catalog](https://thredds.sams.ac.uk/thredds/catalog/scoats-test/COMPASS_NEATL_2020/catalog.html), also from the SAMS thredds server but not directly from the WestCOMS repository.

Interested in any ideas or potential explanation, but also appreciate this might be an issue unrelated with fvcom.tbx so apologies if not appropriate to post here.

Thanks in advance !

Morgane

**Comment by edwardlavender** [comment]
Thanks for your message. Can you include a reproducible example that leads to the error? I will then look into it.

**Comment by morgane-pommier** [comment]
Thank you !

Here is an example of the code I am using:

```
Folder <- "E:/4_Islay Front Chapter/COMPASS_env" #The folder in which the data will be stored

SAMS2020 <- "https://thredds.sams.ac.uk/thredds/catalog/scoats-test/COMPASS_NEATL_2020/catalog.html"
Dates2020 <- seq(as.Date("2020-01-01"), as.Date("2020-01-31"), by="days")
Dates2020 <- format(Dates2020,"%Y%m%d")
Dates2020 <- as.character(Dates2020)
Names2020 <- paste("COMPASS_NEATL_",Dates2020, sep="")

thredds_download(file_name = Names2020,
                 pattern = ".nc",
                 server_catalog = SAMS2020,
                 dest_file = Folder,
                 verbose = TRUE,
                 prompt = FALSE,
                 mode="wb")

#Trying to open one of the files for a test. 
test <- nc_open("E:/4_Islay Front Chapter/COMPASS_env/COMPASS_NEATL_20200102.nc") #Here is where it crashes
test <- stack("E:/4_Islay Front Chapter/COMPASS_env/COMPASS_NEATL_20200102.nc") #Same issue.
```

**Comment by edwardlavender** [comment]
Thanks for providing the code. I have updated the `thredds_download()` function. 

Here is a reproducible adaptation of your code. Does this work for you?

```r
# Install updated package
devtools::install_github("edwardlavender/fvcom.tbx")
library(fvcom.tbx)

# Define temporary directory in which to store file(s)
Folder <- tempdir()

# Define file names
SAMS2020 <- "https://thredds.sams.ac.uk/thredds/catalog/scoats-test/COMPASS_NEATL_2020/catalog.html"
Dates2020 <- seq(as.Date("2020-01-01"), as.Date("2020-01-31"), by="days")
Dates2020 <- format(Dates2020,"%Y%m%d")
Dates2020 <- as.character(Dates2020)
Names2020 <- paste("COMPASS_NEATL_",Dates2020, sep="")

# Download an example file (for speed)
eg <- Names2020[2]
thredds_download(file_name = eg,
                 pattern = ".nc",
                 server_catalog = SAMS2020,
                 dest_file = Folder,
                 verbose = TRUE,
                 prompt = FALSE,
                 mode="wb")

# Define path to file
f <- file.path(Folder, paste0(eg, ".nc"))
file.exists(f)

# Open file
ncdf4::nc_open(f)
raster::stack(f)
```

**Comment by morgane-pommier** [comment]
It works perfectly yes ! Thank you so much for having taken the time to look into it and updating the function !
