### ISSUE TITLE
Dependency 'rgeos' is not available for package 'fvcom.tbx'

### ISSUE THREAD

**Issue by kayihle** [edwardlavender/fvcom.tbx#3]
Hello Edward,

Thanks for creating this package, I am really excited about its functionality!

When installing fvcom.tbx, the following message shows up: "ERROR: dependency 'rgeos' is not available for package 'fvcom.tbx' ". Indeed, rgeos seems to be removed from CRAN, and although older versions could theoretically be installed, it poses some problems for people like me with only moderate R knowledge. https://cran.r-project.org/web/packages/rgeos/index.html

Are there ways to use fvcom.tbx without rgeos? 

Many thanks,
Kay

**Comment by edwardlavender** [comment]
Thanks for your interest. This package has unfortunately not been keep up-to-date with the evolution of R's spatial ecosystem, especially the archival of `rgeos` in October 2023. 

I have updated the package with a temporary fix to remove the installation requirement for `rgeos`. You can now install the package as follows:

```
# Install suggested packages, excluding rgeos
install.packages(c("xml2", "rvest", "ncdf4",
                   "microbenchmark", 
                   "knitr", "rmarkdown", "scales", "terra"))

# Install fvcom.tbx, with hard dependencies
devtools::install_github("edwardlavender/fvcom.tbx", dependencies = "Imports")
```

You can try including ` build_vignettes = TRUE` in the `install_github` function above. View the vignette with `vignette("fvcom_toolbox_vignette")`.  Vignette building during package installation may if you do not have external dependencies installed. If so, just drop it from the function call. I can email you the vignette in this case if you need it. 

The hard requirement for `rgeos` was only in the `build_mesh()` function, where `terra` is now used instead. This function is now quite a bit slower but will work without `rgeos`. I am not sure if `rgeos` is used implicitly elsewhere by any other packages used in `fvcom.tbx`---hopefully this is not the case. Please note that the package was developed a few years ago on an older R version, so keep an eye out for unexpected behaviour if you're using more recent R versions and packages. I hope this gets you up and running for now.

**Comment by kayihle** [comment]
Hello Edward,

Thanks a lot for the fast response and the changes! It worked, installation
was succesful!
I am excited to start exploring the functionality of fvcom.tbx and I will
keep an eye out for unexpected behaviour.

Again, many thanks!
Kay
